apiVersion: v1
kind: Service
metadata:
  name: maildev-service
spec:
  selector:
    app: maildev
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 1080
    - protocol: TCP
      port: 1025
      targetPort: 1025
